// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"animatedSVEnemies","status":true,"description":"Version: 1.16a - The Re-Remake\n- Lets enemies be animated!","parameters":{"Debug":"true","No Movement":"false","Enemies Celebrate":"true","SV Enemies Collapse":"false","Static Enemies Breathe":"true","AGI Effects Breathing":"true","Scale Statics by Distance":"true","Damage Slows Down Breathing":"true"}}
];
